import os
from dotenv import load_dotenv

load_dotenv()

DB_URL = os.environ["DB_URL"]
REDIS_URL = os.environ["REDIS_URL"]
FETCH_INTERVAL = int(os.getenv("FETCH_INTERVAL", "30"))
ARBITRAGE_THRESHOLD = float(os.getenv("ARBITRAGE_THRESHOLD", "1"))

STOCKS = [
    ("ADANIENT.NS",   "ADANIENT.BO"),
    ("ADANIPORTS.NS", "ADANIPORTS.BO"),
    ("APOLLOHOSP.NS", "APOLLOHOSP.BO"),
    ("ASIANPAINT.NS", "ASIANPAINT.BO"),
    ("AXISBANK.NS",   "AXISBANK.BO"),
    ("BAJAJ-AUTO.NS", "BAJAJ-AUTO.BO"),
    ("BAJAJFINSV.NS", "BAJAJFINSV.BO"),
    ("BAJFINANCE.NS", "BAJFINANCE.BO"),
    ("BEL.NS",        "BEL.BO"),
    ("BHARTIARTL.NS", "BHARTIARTL.BO"),
    ("BPCL.NS",       "BPCL.BO"),
    ("BRITANNIA.NS",  "BRITANNIA.BO"),
    ("CIPLA.NS",      "CIPLA.BO"),
    ("COALINDIA.NS",  "COALINDIA.BO"),
    ("DIVISLAB.NS",   "DIVISLAB.BO"),
    ("DRREDDY.NS",    "DRREDDY.BO"),
    ("EICHERMOT.NS",  "EICHERMOT.BO"),
    ("GRASIM.NS",     "GRASIM.BO"),
    ("HCLTECH.NS",    "HCLTECH.BO"),
    ("HDFCBANK.NS",   "HDFCBANK.BO"),
    ("HDFCLIFE.NS",   "HDFCLIFE.BO"),
    ("HEROMOTOCO.NS", "HEROMOTOCO.BO"),
    ("HINDALCO.NS",   "HINDALCO.BO"),
    ("HINDUNILVR.NS", "HINDUNILVR.BO"),
    ("ICICIBANK.NS",  "ICICIBANK.BO"),
    ("INDUSINDBK.NS", "INDUSINDBK.BO"),
    ("INFY.NS",       "INFY.BO"),
    ("ITC.NS",        "ITC.BO"),
    ("JSWSTEEL.NS",   "JSWSTEEL.BO"),
    ("KOTAKBANK.NS",  "KOTAKBANK.BO"),
    ("LT.NS",         "LT.BO"),
    ("M&M.NS",        "M&M.BO"),
    ("MARUTI.NS",     "MARUTI.BO"),
    ("NESTLEIND.NS",  "NESTLEIND.BO"),
    ("NTPC.NS",       "NTPC.BO"),
    ("ONGC.NS",       "ONGC.BO"),
    ("POWERGRID.NS",  "POWERGRID.BO"),
    ("RELIANCE.NS",   "RELIANCE.BO"),
    ("SBIN.NS",       "SBIN.BO"),
    ("SHRIRAMFIN.NS", "SHRIRAMFIN.BO"),
    ("SUNPHARMA.NS",  "SUNPHARMA.BO"),
    ("TATAMOTORS.NS", "TATAMOTORS.BO"),
    ("TATASTEEL.NS",  "TATASTEEL.BO"),
    ("TCS.NS",        "TCS.BO"),
    ("TECHM.NS",      "TECHM.BO"),
    ("TITAN.NS",      "TITAN.BO"),
    ("TATACONSUM.NS", "TATACONSUM.BO"),
    ("TRENT.NS",      "TRENT.BO"),
    ("ULTRACEMCO.NS", "ULTRACEMCO.BO"),
    ("WIPRO.NS",      "WIPRO.BO"),
]

BSE_SCRIP_CODES = {
    "ADANIENT.BO":   "512599",
    "ADANIPORTS.BO": "532921",
    "APOLLOHOSP.BO": "508869",
    "ASIANPAINT.BO": "500820",
    "AXISBANK.BO":   "532215",
    "BAJAJ-AUTO.BO": "532977",
    "BAJAJFINSV.BO": "532978",
    "BAJFINANCE.BO": "500034",
    "BEL.BO":        "500049",
    "BHARTIARTL.BO": "532454",
    "BPCL.BO":       "500547",
    "BRITANNIA.BO":  "500825",
    "CIPLA.BO":      "500087",
    "COALINDIA.BO":  "533278",
    "DIVISLAB.BO":   "532488",
    "DRREDDY.BO":    "500124",
    "EICHERMOT.BO":  "505200",
    "GRASIM.BO":     "500300",
    "HCLTECH.BO":    "532281",
    "HDFCBANK.BO":   "500180",
    "HDFCLIFE.BO":   "540777",
    "HEROMOTOCO.BO": "500182",
    "HINDALCO.BO":   "500440",
    "HINDUNILVR.BO": "500696",
    "ICICIBANK.BO":  "532174",
    "INDUSINDBK.BO": "532187",
    "INFY.BO":       "500209",
    "ITC.BO":        "500875",
    "JSWSTEEL.BO":   "500228",
    "KOTAKBANK.BO":  "500247",
    "LT.BO":         "500510",
    "M&M.BO":        "500520",
    "MARUTI.BO":     "532500",
    "NESTLEIND.BO":  "500790",
    "NTPC.BO":       "532555",
    "ONGC.BO":       "500312",
    "POWERGRID.BO":  "532898",
    "RELIANCE.BO":   "500325",
    "SBIN.BO":       "500112",
    "SHRIRAMFIN.BO": "530655",
    "SUNPHARMA.BO":  "524715",
    "TATAMOTORS.BO": "500570",
    "TATASTEEL.BO":  "500470",
    "TCS.BO":        "532540",
    "TECHM.BO":      "532755",
    "TITAN.BO":      "500114",
    "TATACONSUM.BO": "500800",
    "TRENT.BO":      "500251",
    "ULTRACEMCO.BO": "532538",
    "WIPRO.BO":      "507685",
}
